version: "3.8"

services:
  discord-lavalink-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: myorg/discord-lavalink-music-bot:latest
    container_name: discord-lavalink-music-bot
    env_file:
      - .env
    ports:
      - "8080:8080" # remove if unused
    restart: unless-stopped
    networks:
      - bot_net

networks:
  bot_net:
    driver: bridge
